name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - run: ls /home/runner/work/IT-Automation_2026/IT-Automation_2026/UltimateApp/bin/
    - run: ls /home/runner/work/IT-Automation_2026/IT-Automation_2026/UltimateApp/bin/Debug/net8.0/
      continue-on-error: true
    - run: ls /home/runner/work/IT-Automation_2026/IT-Automation_2026/UltimateApp/bin/Release/net8.0/
    - name: Create Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: "/home/runner/work/IT-Automation_2026/IT-Automation_2026/UltimateApp/bin/Release/net8.0/UltimateApp"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "0.1"
