name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v6
    - name: Create an Issue
      uses: JasonEtco/create-an-issue@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          filename: .github/ultimate_issue_template.md
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Debug
    - name: Test
      run: dotnet test --no-restore --verbosity normal --logger trx --results-directory "TestResults"
    - name: Publish Test 
      uses: dorny/test-reporter@v3
      if: always()
      with:
        name: Test Results on dev
        path: ./TestResults/*.trx
        reporter: dotnet-trx
    - name: Create an Issue
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ultimate_issue_template.md
    
    - name: Compress Release
      run: tar -czvf calculator.tar.gz -C /home/runner/work/IT-Automation_2026/IT-Automation_2026/UltimateApp/bin/Release/net8.0/ .
    - name: Publish Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: calculator.tar.gz
        #artifacts: "/home/runner/work/IT-Automation_2026/IT-Automation_2026/UltimateApp/bin/Release/net8.0/"
        #token: ${{ secrets.GITHUB_TOKEN }}
        tag: "0.41"
